apiVersion: apps/v1
kind: Deployment
metadata:
  name: authelia
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: authelia
  template:
    metadata:
      labels:
        app.kubernetes.io/name: authelia
    spec:
      automountServiceAccountToken: false
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
      containers:
        - name: authelia
          image: authelia
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            allowPrivilegeEscalation: false
          envFrom:
            - configMapRef:
                name: authelia-secrets-env
          command:
            - authelia
          args:
            - '--config'
            - '/config/configuration.yml'
          ports:
            - containerPort: 9091
              name: http
          volumeMounts:
            - mountPath: /config
              name: authelia-config
            - mountPath: /secrets
              name: authelia-secrets
              readOnly: true
      volumes:
        - name: authelia-config
          configMap:
            name: authelia-config
        - name: authelia-secrets-env
          configMap:
            name: authelia-secrets-env
        - name: authelia-secrets
          secret:
            secretName: authelia-secrets

