apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: authelia
    newName: ghcr.io/authelia/authelia
    newTag: 4.34.4

configMapGenerator:
  - name: authelia-secrets-env
    literals:
      - AUTHELIA_TLS_KEY_FILE=/secrets/tls_key
      - AUTHELIA_JWT_SECRET_FILE=/secrets/jwt_secret
      - AUTHELIA_DUO_API_SECRET_KEY_FILE=/secrets/duo_api.secret_key
      - AUTHELIA_SESSION_SECRET_FILE=/secrets/session.secret
      - AUTHELIA_SESSION_REDIS_PASSWORD_FILE=/secrets/session.redis.password
      - AUTHELIA_REDIS_HIGH_AVAILABILITY_SENTINEL_PASSWORD_FILE=/secrets/session.redis.high_availability.sentinel_password
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/secrets/storage.encryption_key
      - AUTHELIA_STORAGE_MYSQL_PASSWORD_FILE=/secrets/storage.mysql.password
      - AUTHELIA_STORAGE_POSTGRES_PASSWORD_FILE=/secrets/storage.postgres.password
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/secrets/notifier.smtp.password
      - AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE=/secrets/authentication_backend.ldap.password
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_ISSUER_PRIVATE_KEY_FILE=/secrets/identity_providers.oidc.issuer_private_key
      - AUTHELIA_IDENTITY_PROVIDERS_OIDC_HMAC_SECRET_FILE=/secrets/identity_providers.oidc.hmac_secret
  - name: authelia-config
    files:
      - configuration.yml

secretGenerator:
  - name: authelia-secrets
    literals:
      - tls_key=
      - jwt_secret=
      - duo_api.secret_key=
      - session.secret=
      - session.redis.password=
      - session.redis.high_availability.sentinel_password=
      - storage.encryption_key=
      - storage.mysql.password=
      - storage.postgres.password=
      - notifier.smtp.password=
      - authentication_backend.ldap.password=
      - identity_providers.oidc.issuer_private_key=
      - identity_providers.oidc.hmac_secret=
